language: c

sudo: false

env:
  global:
    - LUAROCKS=2.4.3
  matrix:
    - LUA=lua5.3

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install busted

script:
  - busted spec

after_success:
  - coveralls -b .. -r .. -i ./src --dump c.report.json
  - luacov-coveralls -j c.report.json -v
